pub(crate) const PLASMA_PARTICLE_TEXTURE_SIZE: u32 = 64;

pub(crate) const PLASMA_CORE_PARTICLE_SIZE: f32 = 20.0;
pub(crate) const PLASMA_GLOW_PARTICLE_SIZE: f32 = 28.0;
pub(crate) const PLASMA_ARC_PARTICLE_SIZE: f32 = 22.0;

pub(crate) const PLASMA_CORE_WIDTH: f32 = 8.5;
pub(crate) const PLASMA_GLOW_WIDTH: f32 = 18.0;
pub(crate) const PLASMA_ARC_AMPLITUDE: f32 = 4.0;

pub(crate) const PLASMA_IMPACT_BURST_SIZE_MIN: f32 = PLASMA_CORE_PARTICLE_SIZE * 0.65;
pub(crate) const PLASMA_IMPACT_BURST_SIZE_RANGE: f32 = PLASMA_GLOW_PARTICLE_SIZE * 0.25;

pub(crate) const PLASMA_IMPACT_AFTERGLOW_SIZE_MIN: f32 = PLASMA_GLOW_PARTICLE_SIZE * 0.55;
pub(crate) const PLASMA_IMPACT_AFTERGLOW_SIZE_RANGE: f32 = PLASMA_GLOW_PARTICLE_SIZE * 0.3;

pub(crate) const PLASMA_IMPACT_ARC_SIZE_MIN: f32 = PLASMA_ARC_PARTICLE_SIZE * 0.45;
pub(crate) const PLASMA_IMPACT_ARC_SIZE_RANGE: f32 = PLASMA_ARC_PARTICLE_SIZE * 0.20;

