pub mod collider;
pub mod rigid_body;
pub mod health;
pub mod auto_movement;
pub mod controlled_movement;
pub mod controlled_range_attack;
pub mod auto_range_attack;
pub mod auto_melee_attack;
pub mod controlled_melee_attack;
pub mod player_input;
pub mod blocking;
pub mod gravity;
pub mod state_machine;
pub mod animation_config;
pub mod game_entity;
pub mod player_tag;
pub mod enemy_tag;
pub mod environment_tag;
pub mod doodad_tag;

// Re-exports for convenience
pub use collider::{Collider, ColliderShape};
pub use rigid_body::RigidBody;
pub use health::Health;
pub use auto_movement::AutoMovement;
pub use controlled_movement::ControlledMovement;
pub use controlled_range_attack::ControlledRangeAttack;
pub use auto_range_attack::AutoRangeAttack;
pub use auto_melee_attack::AutoMeleeAttack;
pub use controlled_melee_attack::ControlledMeleeAttack;
pub use player_input::PlayerInput;
pub use blocking::Blocking;
pub use gravity::Gravity;
pub use state_machine::{StateMachine, EntityState};
pub use animation_config::AnimationConfig;
pub use game_entity::GameEntity;
pub use player_tag::PlayerTag;
pub use enemy_tag::EnemyTag;
pub use environment_tag::EnvironmentTag;
pub use doodad_tag::DoodadTag;
